export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          avatar_url: string | null;
          trial_start_at: string | null;
          trial_expires_at: string | null;
          industry_type: string | null;
          bot_platform: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          full_name: string;
          avatar_url?: string | null;
          trial_start_at?: string | null;
          trial_expires_at?: string | null;
          industry_type?: string | null;
          bot_platform?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          avatar_url?: string | null;
          trial_start_at?: string | null;
          trial_expires_at?: string | null;
          industry_type?: string | null;
          bot_platform?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      tenants: {
        Row: {
          id: string;
          name: string;
          industry: "ecommerce" | "restaurant" | "fnb" | "beauty" | "service";
          status: "active" | "trial" | "suspended" | "cancelled";
          plan: "trial" | "starter" | "pro" | "business";
          owner_id: string;
          whatsapp_phone_id: string | null;
          whatsapp_token: string | null;
          telegram_bot_token: string | null;
          telegram_chat_id: string | null;
          logo_url: string | null;
          subdomain: string | null;
          settings: Record<string, unknown>;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          industry: "ecommerce" | "restaurant" | "fnb" | "beauty" | "service";
          status?: "active" | "trial" | "suspended" | "cancelled";
          plan?: "trial" | "starter" | "pro" | "business";
          owner_id: string;
          whatsapp_phone_id?: string | null;
          whatsapp_token?: string | null;
          telegram_bot_token?: string | null;
          telegram_chat_id?: string | null;
          logo_url?: string | null;
          subdomain?: string | null;
          settings?: Record<string, unknown>;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          industry?: "ecommerce" | "restaurant" | "fnb" | "beauty" | "service";
          status?: "active" | "trial" | "suspended" | "cancelled";
          plan?: "trial" | "starter" | "pro" | "business";
          owner_id?: string;
          whatsapp_phone_id?: string | null;
          whatsapp_token?: string | null;
          telegram_bot_token?: string | null;
          telegram_chat_id?: string | null;
          logo_url?: string | null;
          subdomain?: string | null;
          settings?: Record<string, unknown>;
          created_at?: string;
        };
        Relationships: [];
      };
      tenant_users: {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string;
          role: "super_admin" | "tenant_owner" | "tenant_admin" | "staff" | "customer";
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id: string;
          role?: "super_admin" | "tenant_owner" | "tenant_admin" | "staff" | "customer";
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          user_id?: string;
          role?: "super_admin" | "tenant_owner" | "tenant_admin" | "staff" | "customer";
          created_at?: string;
        };
        Relationships: [];
      };
      contacts: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          phone: string;
          email: string | null;
          tags: string[];
          stage: "new_inquiry" | "quoted" | "follow_up" | "closed_won" | "closed_lost";
          notes: string | null;
          company: string | null;
          address: string | null;
          source: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          phone: string;
          email?: string | null;
          tags?: string[];
          stage?: "new_inquiry" | "quoted" | "follow_up" | "closed_won" | "closed_lost";
          notes?: string | null;
          company?: string | null;
          address?: string | null;
          source?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          phone?: string;
          email?: string | null;
          tags?: string[];
          stage?: "new_inquiry" | "quoted" | "follow_up" | "closed_won" | "closed_lost";
          notes?: string | null;
          company?: string | null;
          address?: string | null;
          source?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      conversations: {
        Row: {
          id: string;
          tenant_id: string;
          contact_id: string;
          last_message: string | null;
          last_message_at: string | null;
          unread_count: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          contact_id: string;
          last_message?: string | null;
          last_message_at?: string | null;
          unread_count?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          contact_id?: string;
          last_message?: string | null;
          last_message_at?: string | null;
          unread_count?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          tenant_id: string;
          direction: "inbound" | "outbound";
          content: string;
          message_type: "text" | "image" | "document" | "template";
          status: "sent" | "delivered" | "read" | "failed";
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          tenant_id: string;
          direction: "inbound" | "outbound";
          content: string;
          message_type?: "text" | "image" | "document" | "template";
          status?: "sent" | "delivered" | "read" | "failed";
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          tenant_id?: string;
          direction?: "inbound" | "outbound";
          content?: string;
          message_type?: "text" | "image" | "document" | "template";
          status?: "sent" | "delivered" | "read" | "failed";
          created_at?: string;
        };
        Relationships: [];
      };
      products: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          name_en: string | null;
          name_zh: string | null;
          description: string | null;
          price: string;
          currency: string;
          stock: number | null;
          category: string | null;
          image_url: string | null;
          images: string[];
          sku: string | null;
          brand: string | null;
          weight: number | null;
          unit: string | null;
          tags: string[];
          discount_type: "percentage" | "fixed" | null;
          discount_value: number | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          name_en?: string | null;
          name_zh?: string | null;
          description?: string | null;
          price: string;
          currency?: string;
          stock?: number | null;
          category?: string | null;
          image_url?: string | null;
          images?: string[];
          sku?: string | null;
          brand?: string | null;
          weight?: number | null;
          unit?: string | null;
          tags?: string[];
          discount_type?: "percentage" | "fixed" | null;
          discount_value?: number | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          name_en?: string | null;
          name_zh?: string | null;
          description?: string | null;
          price?: string;
          currency?: string;
          stock?: number | null;
          category?: string | null;
          image_url?: string | null;
          images?: string[];
          sku?: string | null;
          brand?: string | null;
          weight?: number | null;
          unit?: string | null;
          tags?: string[];
          discount_type?: "percentage" | "fixed" | null;
          discount_value?: number | null;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      orders: {
        Row: {
          id: string;
          tenant_id: string;
          contact_id: string;
          status: "draft" | "confirmed" | "shipped" | "completed" | "cancelled";
          total: string;
          currency: string;
          items: Record<string, unknown>[];
          notes: string | null;
          shipping_address: string | null;
          shipping_city: string | null;
          shipping_state: string | null;
          shipping_postal_code: string | null;
          shipping_country: string | null;
          payment_status: "unpaid" | "partial" | "paid" | "refunded";
          payment_method: string | null;
          paid_at: string | null;
          shipment_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          contact_id: string;
          status?: "draft" | "confirmed" | "shipped" | "completed" | "cancelled";
          total: string;
          currency?: string;
          items?: Record<string, unknown>[];
          notes?: string | null;
          shipping_address?: string | null;
          shipping_city?: string | null;
          shipping_state?: string | null;
          shipping_postal_code?: string | null;
          shipping_country?: string | null;
          payment_status?: "unpaid" | "partial" | "paid" | "refunded";
          payment_method?: string | null;
          paid_at?: string | null;
          shipment_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          contact_id?: string;
          status?: "draft" | "confirmed" | "shipped" | "completed" | "cancelled";
          total?: string;
          currency?: string;
          items?: Record<string, unknown>[];
          notes?: string | null;
          shipping_address?: string | null;
          shipping_city?: string | null;
          shipping_state?: string | null;
          shipping_postal_code?: string | null;
          shipping_country?: string | null;
          payment_status?: "unpaid" | "partial" | "paid" | "refunded";
          payment_method?: string | null;
          paid_at?: string | null;
          shipment_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      follow_ups: {
        Row: {
          id: string;
          tenant_id: string;
          contact_id: string;
          contact_name: string | null;
          type: "manual" | "automated";
          message: string;
          scheduled_at: string;
          status: "pending" | "completed" | "overdue" | "cancelled";
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          contact_id: string;
          contact_name?: string | null;
          type?: "manual" | "automated";
          message: string;
          scheduled_at: string;
          status?: "pending" | "completed" | "overdue" | "cancelled";
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          contact_id?: string;
          contact_name?: string | null;
          type?: "manual" | "automated";
          message?: string;
          scheduled_at?: string;
          status?: "pending" | "completed" | "overdue" | "cancelled";
          created_at?: string;
        };
        Relationships: [];
      };
      plans: {
        Row: {
          id: string;
          name: string;
          tier: "trial" | "starter" | "pro" | "business";
          price_monthly: string;
          features: string[];
          limits: Record<string, unknown>;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          name: string;
          tier: "trial" | "starter" | "pro" | "business";
          price_monthly: string;
          features?: string[];
          limits?: Record<string, unknown>;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          name?: string;
          tier?: "trial" | "starter" | "pro" | "business";
          price_monthly?: string;
          features?: string[];
          limits?: Record<string, unknown>;
          is_active?: boolean;
        };
        Relationships: [];
      };
      feature_flags: {
        Row: {
          id: string;
          key: string;
          name: string;
          description: string | null;
          icon: string | null;
          is_core: boolean;
          is_enabled: boolean;
          plans: string[];
        };
        Insert: {
          id?: string;
          key: string;
          name: string;
          description?: string | null;
          icon?: string | null;
          is_core?: boolean;
          is_enabled?: boolean;
          plans?: string[];
        };
        Update: {
          id?: string;
          key?: string;
          name?: string;
          description?: string | null;
          icon?: string | null;
          is_core?: boolean;
          is_enabled?: boolean;
          plans?: string[];
        };
        Relationships: [];
      };
      case_studies: {
        Row: {
          id: string;
          title: string;
          industry: "ecommerce" | "restaurant" | "fnb" | "beauty" | "service";
          description: string;
          metrics: Record<string, unknown>;
          screenshots: string[];
          is_published: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          industry: "ecommerce" | "restaurant" | "fnb" | "beauty" | "service";
          description: string;
          metrics?: Record<string, unknown>;
          screenshots?: string[];
          is_published?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          industry?: "ecommerce" | "restaurant" | "fnb" | "beauty" | "service";
          description?: string;
          metrics?: Record<string, unknown>;
          screenshots?: string[];
          is_published?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      webhook_logs: {
        Row: {
          id: string;
          tenant_id: string;
          event_type: string;
          payload: Record<string, unknown>;
          status: "success" | "failed";
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          event_type: string;
          payload?: Record<string, unknown>;
          status: "success" | "failed";
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          event_type?: string;
          payload?: Record<string, unknown>;
          status?: "success" | "failed";
          error_message?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      support_tickets: {
        Row: {
          id: string;
          tenant_id: string;
          from_name: string | null;
          subject: string;
          description: string;
          status: "open" | "in_progress" | "resolved" | "closed";
          priority: "low" | "medium" | "high" | "urgent";
          channel: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          from_name?: string | null;
          subject: string;
          description: string;
          status?: "open" | "in_progress" | "resolved" | "closed";
          priority?: "low" | "medium" | "high" | "urgent";
          channel?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          from_name?: string | null;
          subject?: string;
          description?: string;
          status?: "open" | "in_progress" | "resolved" | "closed";
          priority?: "low" | "medium" | "high" | "urgent";
          channel?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      campaigns: {
        Row: {
          id: string;
          tenant_id: string | null;
          name: string;
          platform: string;
          status: "active" | "paused" | "draft" | "completed";
          budget: string;
          spent: string;
          leads: number;
          cost_per_lead: string | null;
          roas: string | null;
          currency: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          name: string;
          platform?: string;
          status?: "active" | "paused" | "draft" | "completed";
          budget?: string;
          spent?: string;
          leads?: number;
          cost_per_lead?: string | null;
          roas?: string | null;
          currency?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string | null;
          name?: string;
          platform?: string;
          status?: "active" | "paused" | "draft" | "completed";
          budget?: string;
          spent?: string;
          leads?: number;
          cost_per_lead?: string | null;
          roas?: string | null;
          currency?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      automations: {
        Row: {
          id: string;
          tenant_id: string | null;
          name: string;
          type: "trigger" | "sequence" | "scheduled" | "ai";
          description: string | null;
          is_enabled: boolean;
          tenants_using: number;
          fired_count: number;
          is_template: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          name: string;
          type?: "trigger" | "sequence" | "scheduled" | "ai";
          description?: string | null;
          is_enabled?: boolean;
          tenants_using?: number;
          fired_count?: number;
          is_template?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string | null;
          name?: string;
          type?: "trigger" | "sequence" | "scheduled" | "ai";
          description?: string | null;
          is_enabled?: boolean;
          tenants_using?: number;
          fired_count?: number;
          is_template?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      referrals: {
        Row: {
          id: string;
          tenant_id: string | null;
          customer_name: string | null;
          referral_count: number;
          conversions: number;
          commission: string;
          earned: string;
          reward: string | null;
          currency: string;
          status: "active" | "pending" | "paused" | "completed";
          context: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          customer_name?: string | null;
          referral_count?: number;
          conversions?: number;
          commission?: string;
          earned?: string;
          reward?: string | null;
          currency?: string;
          status?: "active" | "pending" | "paused" | "completed";
          context?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string | null;
          customer_name?: string | null;
          referral_count?: number;
          conversions?: number;
          commission?: string;
          earned?: string;
          reward?: string | null;
          currency?: string;
          status?: "active" | "pending" | "paused" | "completed";
          context?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      landing_pages: {
        Row: {
          id: string;
          tenant_id: string | null;
          name: string;
          status: "published" | "draft" | "archived";
          visits: number;
          conversions: number;
          template: "ecommerce" | "restaurant" | "fnb" | "beauty" | "service";
          updated_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          name: string;
          status?: "published" | "draft" | "archived";
          visits?: number;
          conversions?: number;
          template: "ecommerce" | "restaurant" | "fnb" | "beauty" | "service";
          updated_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string | null;
          name?: string;
          status?: "published" | "draft" | "archived";
          visits?: number;
          conversions?: number;
          template?: "ecommerce" | "restaurant" | "fnb" | "beauty" | "service";
          updated_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      design_assets: {
        Row: {
          id: string;
          name: string;
          type: string;
          format: string;
          uses: number;
          image_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: string;
          format: string;
          uses?: number;
          image_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: string;
          format?: string;
          uses?: number;
          image_url?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      industry_templates: {
        Row: {
          id: string;
          key: string;
          label: string;
          industry: "ecommerce" | "restaurant" | "fnb" | "beauty" | "service";
          version: string;
          components: Record<string, unknown>[];
          updated_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          label: string;
          industry: "ecommerce" | "restaurant" | "fnb" | "beauty" | "service";
          version?: string;
          components?: Record<string, unknown>[];
          updated_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          label?: string;
          industry?: "ecommerce" | "restaurant" | "fnb" | "beauty" | "service";
          version?: string;
          components?: Record<string, unknown>[];
          updated_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      appointments: {
        Row: {
          id: string;
          tenant_id: string | null;
          client_name: string;
          service: string;
          therapist: string | null;
          date: string;
          time: string;
          duration: string | null;
          status: "pending" | "confirmed" | "completed" | "cancelled";
          contact_id: string | null;
          service_id: string | null;
          therapist_id: string | null;
          price: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          client_name: string;
          service: string;
          therapist?: string | null;
          date: string;
          time: string;
          duration?: string | null;
          status?: "pending" | "confirmed" | "completed" | "cancelled";
          contact_id?: string | null;
          service_id?: string | null;
          therapist_id?: string | null;
          price?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string | null;
          client_name?: string;
          service?: string;
          therapist?: string | null;
          date?: string;
          time?: string;
          duration?: string | null;
          status?: "pending" | "confirmed" | "completed" | "cancelled";
          contact_id?: string | null;
          service_id?: string | null;
          therapist_id?: string | null;
          price?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      reservations: {
        Row: {
          id: string;
          tenant_id: string | null;
          guest_name: string;
          date: string;
          time: string;
          pax: number;
          table_label: string | null;
          status: "pending" | "confirmed" | "seated" | "completed" | "cancelled";
          note: string | null;
          contact_id: string | null;
          phone: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          guest_name: string;
          date: string;
          time: string;
          pax?: number;
          table_label?: string | null;
          status?: "pending" | "confirmed" | "seated" | "completed" | "cancelled";
          note?: string | null;
          contact_id?: string | null;
          phone?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string | null;
          guest_name?: string;
          date?: string;
          time?: string;
          pax?: number;
          table_label?: string | null;
          status?: "pending" | "confirmed" | "seated" | "completed" | "cancelled";
          note?: string | null;
          contact_id?: string | null;
          phone?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      staff: {
        Row: {
          id: string;
          tenant_id: string | null;
          name: string;
          role: string | null;
          specialties: string[];
          rating: string | null;
          today_bookings: number;
          weekly_hours: number;
          status: "available" | "busy" | "off";
          image_url: string | null;
          phone: string | null;
          email: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          name: string;
          role?: string | null;
          specialties?: string[];
          rating?: string | null;
          today_bookings?: number;
          weekly_hours?: number;
          status?: "available" | "busy" | "off";
          image_url?: string | null;
          phone?: string | null;
          email?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string | null;
          name?: string;
          role?: string | null;
          specialties?: string[];
          rating?: string | null;
          today_bookings?: number;
          weekly_hours?: number;
          status?: "available" | "busy" | "off";
          image_url?: string | null;
          phone?: string | null;
          email?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      restaurant_tables: {
        Row: {
          id: string;
          tenant_id: string | null;
          table_number: string;
          seats: number;
          zone: string;
          status: "available" | "occupied" | "reserved" | "cleaning";
          guest_name: string | null;
          occupied_since: string | null;
          reserved_time: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          table_number: string;
          seats?: number;
          zone?: string;
          status?: "available" | "occupied" | "reserved" | "cleaning";
          guest_name?: string | null;
          occupied_since?: string | null;
          reserved_time?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string | null;
          table_number?: string;
          seats?: number;
          zone?: string;
          status?: "available" | "occupied" | "reserved" | "cleaning";
          guest_name?: string | null;
          occupied_since?: string | null;
          reserved_time?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      shipments: {
        Row: {
          id: string;
          tenant_id: string | null;
          order_id: string | null;
          customer_name: string;
          courier: string | null;
          tracking_number: string | null;
          destination: string | null;
          status: "pending" | "shipped" | "in_transit" | "completed" | "returned";
          shipped_date: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          order_id?: string | null;
          customer_name: string;
          courier?: string | null;
          tracking_number?: string | null;
          destination?: string | null;
          status?: "pending" | "shipped" | "in_transit" | "completed" | "returned";
          shipped_date?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string | null;
          order_id?: string | null;
          customer_name?: string;
          courier?: string | null;
          tracking_number?: string | null;
          destination?: string | null;
          status?: "pending" | "shipped" | "in_transit" | "completed" | "returned";
          shipped_date?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      deliveries: {
        Row: {
          id: string;
          tenant_id: string | null;
          order_id: string | null;
          customer_name: string;
          address: string | null;
          rider: string | null;
          status: "pending" | "confirmed" | "delivering" | "completed" | "failed";
          eta: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          order_id?: string | null;
          customer_name: string;
          address?: string | null;
          rider?: string | null;
          status?: "pending" | "confirmed" | "delivering" | "completed" | "failed";
          eta?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string | null;
          order_id?: string | null;
          customer_name?: string;
          address?: string | null;
          rider?: string | null;
          status?: "pending" | "confirmed" | "delivering" | "completed" | "failed";
          eta?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      transactions: {
        Row: {
          id: string;
          tenant_id: string | null;
          order_id: string | null;
          customer_name: string;
          amount: string;
          currency: string;
          method: string;
          status: "pending" | "success" | "failed" | "refunded";
          transaction_date: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          order_id?: string | null;
          customer_name: string;
          amount: string;
          currency?: string;
          method: string;
          status?: "pending" | "success" | "failed" | "refunded";
          transaction_date?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string | null;
          order_id?: string | null;
          customer_name?: string;
          amount?: string;
          currency?: string;
          method?: string;
          status?: "pending" | "success" | "failed" | "refunded";
          transaction_date?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      ai_logs: {
        Row: {
          id: string;
          tenant_id: string;
          tenant_name: string | null;
          model: string;
          tokens: number;
          latency_ms: number | null;
          status: "success" | "failed";
          error_message: string | null;
          request_type: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          tenant_name?: string | null;
          model?: string;
          tokens?: number;
          latency_ms?: number | null;
          status: "success" | "failed";
          error_message?: string | null;
          request_type?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          tenant_name?: string | null;
          model?: string;
          tokens?: number;
          latency_ms?: number | null;
          status?: "success" | "failed";
          error_message?: string | null;
          request_type?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      members: {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string | null;
          name: string;
          phone: string | null;
          email: string | null;
          tags: string[];
          tier: string;
          total_spent: string;
          referral_code: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id?: string | null;
          name: string;
          phone?: string | null;
          email?: string | null;
          tags?: string[];
          tier?: string;
          total_spent?: string;
          referral_code?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          user_id?: string | null;
          name?: string;
          phone?: string | null;
          email?: string | null;
          tags?: string[];
          tier?: string;
          total_spent?: string;
          referral_code?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      subscriptions: {
        Row: {
          id: string;
          tenant_id: string;
          plan_id: string | null;
          status: "trialing" | "active" | "past_due" | "cancelled" | "expired";
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          current_period_start: string | null;
          current_period_end: string | null;
          trial_start_at: string | null;
          trial_expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          plan_id?: string | null;
          status?: "trialing" | "active" | "past_due" | "cancelled" | "expired";
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          current_period_start?: string | null;
          current_period_end?: string | null;
          trial_start_at?: string | null;
          trial_expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          plan_id?: string | null;
          status?: "trialing" | "active" | "past_due" | "cancelled" | "expired";
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          current_period_start?: string | null;
          current_period_end?: string | null;
          trial_start_at?: string | null;
          trial_expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      bot_configs: {
        Row: {
          id: string;
          tenant_id: string;
          platform: string;
          system_prompt: string | null;
          industry_type: string;
          welcome_message: string | null;
          is_active: boolean;
          openclaw_agent_id: string | null;
          config: Record<string, unknown>;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          platform?: string;
          system_prompt?: string | null;
          industry_type: string;
          welcome_message?: string | null;
          is_active?: boolean;
          openclaw_agent_id?: string | null;
          config?: Record<string, unknown>;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          platform?: string;
          system_prompt?: string | null;
          industry_type?: string;
          welcome_message?: string | null;
          is_active?: boolean;
          openclaw_agent_id?: string | null;
          config?: Record<string, unknown>;
          created_at?: string;
        };
        Relationships: [];
      };
      ai_conversations: {
        Row: {
          id: string;
          tenant_id: string;
          contact_id: string | null;
          member_id: string | null;
          title: string | null;
          message_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          contact_id?: string | null;
          member_id?: string | null;
          title?: string | null;
          message_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          contact_id?: string | null;
          member_id?: string | null;
          title?: string | null;
          message_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      ai_messages: {
        Row: {
          id: string;
          conversation_id: string;
          role: string;
          content: string;
          actions: Record<string, unknown> | null;
          feedback: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          role?: string;
          content: string;
          actions?: Record<string, unknown> | null;
          feedback?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          role?: string;
          content?: string;
          actions?: Record<string, unknown> | null;
          feedback?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      inventory_categories: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          name_en: string | null;
          color: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          name_en?: string | null;
          color?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          name_en?: string | null;
          color?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      inventory_items: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          sku: string;
          category_id: string | null;
          stock: number;
          min_stock: number;
          unit: string;
          cost_price: string;
          image_url: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          sku: string;
          category_id?: string | null;
          stock?: number;
          min_stock?: number;
          unit?: string;
          cost_price?: string;
          image_url?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          sku?: string;
          category_id?: string | null;
          stock?: number;
          min_stock?: number;
          unit?: string;
          cost_price?: string;
          image_url?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      inventory_ledger: {
        Row: {
          id: string;
          tenant_id: string;
          item_id: string;
          type: "in" | "out";
          quantity: number;
          movement_type: string;
          note: string | null;
          operator: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          item_id: string;
          type: "in" | "out";
          quantity: number;
          movement_type?: string;
          note?: string | null;
          operator?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          item_id?: string;
          type?: "in" | "out";
          quantity?: number;
          movement_type?: string;
          note?: string | null;
          operator?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      suppliers: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          contact_person: string | null;
          phone: string | null;
          email: string | null;
          address: string | null;
          status: "active" | "inactive";
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          contact_person?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          status?: "active" | "inactive";
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          contact_person?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          status?: "active" | "inactive";
          created_at?: string;
        };
        Relationships: [];
      };
      purchase_orders: {
        Row: {
          id: string;
          tenant_id: string;
          po_number: string;
          supplier_id: string | null;
          supplier_name: string;
          total_amount: string;
          currency: string;
          status: "draft" | "submitted" | "approved" | "received" | "cancelled";
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          po_number: string;
          supplier_id?: string | null;
          supplier_name: string;
          total_amount?: string;
          currency?: string;
          status?: "draft" | "submitted" | "approved" | "received" | "cancelled";
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          po_number?: string;
          supplier_id?: string | null;
          supplier_name?: string;
          total_amount?: string;
          currency?: string;
          status?: "draft" | "submitted" | "approved" | "received" | "cancelled";
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      purchase_order_items: {
        Row: {
          id: string;
          po_id: string;
          item_name: string;
          sku: string | null;
          quantity: number;
          unit_price: string;
          total_price: string;
        };
        Insert: {
          id?: string;
          po_id: string;
          item_name: string;
          sku?: string | null;
          quantity: number;
          unit_price: string;
          total_price: string;
        };
        Update: {
          id?: string;
          po_id?: string;
          item_name?: string;
          sku?: string | null;
          quantity?: number;
          unit_price?: string;
          total_price?: string;
        };
        Relationships: [];
      };
      bills: {
        Row: {
          id: string;
          tenant_id: string;
          bill_number: string;
          vendor: string;
          amount: string;
          currency: string;
          type: "purchase" | "logistics" | "operation" | "other";
          status: "pending" | "paid" | "overdue";
          due_date: string;
          paid_date: string | null;
          category: string | null;
          description: string | null;
          notes: string | null;
          reference_type: string | null;
          reference_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          bill_number: string;
          vendor: string;
          amount: string;
          currency?: string;
          type?: "purchase" | "logistics" | "operation" | "other";
          status?: "pending" | "paid" | "overdue";
          due_date: string;
          paid_date?: string | null;
          category?: string | null;
          description?: string | null;
          notes?: string | null;
          reference_type?: string | null;
          reference_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          bill_number?: string;
          vendor?: string;
          amount?: string;
          currency?: string;
          type?: "purchase" | "logistics" | "operation" | "other";
          status?: "pending" | "paid" | "overdue";
          due_date?: string;
          paid_date?: string | null;
          category?: string | null;
          description?: string | null;
          notes?: string | null;
          reference_type?: string | null;
          reference_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      finance_transactions: {
        Row: {
          id: string;
          tenant_id: string;
          date: string;
          type: "income" | "expense";
          category: string;
          amount: string;
          currency: string;
          description: string | null;
          reference_type: string | null;
          reference_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          date: string;
          type: "income" | "expense";
          category: string;
          amount: string;
          currency?: string;
          description?: string | null;
          reference_type?: string | null;
          reference_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          date?: string;
          type?: "income" | "expense";
          category?: string;
          amount?: string;
          currency?: string;
          description?: string | null;
          reference_type?: string | null;
          reference_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      marketing_campaigns: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          platform: string;
          objective: string | null;
          status: "draft" | "active" | "paused" | "completed";
          budget_type: "daily" | "lifetime";
          budget_amount: string;
          budget_spent: string;
          start_date: string | null;
          end_date: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          platform?: string;
          objective?: string | null;
          status?: "draft" | "active" | "paused" | "completed";
          budget_type?: "daily" | "lifetime";
          budget_amount?: string;
          budget_spent?: string;
          start_date?: string | null;
          end_date?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          platform?: string;
          objective?: string | null;
          status?: "draft" | "active" | "paused" | "completed";
          budget_type?: "daily" | "lifetime";
          budget_amount?: string;
          budget_spent?: string;
          start_date?: string | null;
          end_date?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      marketing_performance: {
        Row: {
          id: string;
          tenant_id: string;
          campaign_id: string | null;
          campaign_name: string | null;
          platform: string;
          date: string;
          impressions: number;
          clicks: number;
          conversions: number;
          spend: string;
          revenue: string;
          ctr: string;
          cpc: string;
          cpm: string;
          roas: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          campaign_id?: string | null;
          campaign_name?: string | null;
          platform?: string;
          date: string;
          impressions?: number;
          clicks?: number;
          conversions?: number;
          spend?: string;
          revenue?: string;
          ctr?: string;
          cpc?: string;
          cpm?: string;
          roas?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          campaign_id?: string | null;
          campaign_name?: string | null;
          platform?: string;
          date?: string;
          impressions?: number;
          clicks?: number;
          conversions?: number;
          spend?: string;
          revenue?: string;
          ctr?: string;
          cpc?: string;
          cpm?: string;
          roas?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      ad_placement_plans: {
        Row: {
          id: string;
          tenant_id: string;
          name: string;
          platform: string;
          status: "draft" | "pending_approval" | "approved" | "active" | "completed" | "rejected";
          total_budget: string;
          currency: string;
          start_date: string | null;
          end_date: string | null;
          kpi_targets: Record<string, unknown>;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          name: string;
          platform?: string;
          status?: "draft" | "pending_approval" | "approved" | "active" | "completed" | "rejected";
          total_budget?: string;
          currency?: string;
          start_date?: string | null;
          end_date?: string | null;
          kpi_targets?: Record<string, unknown>;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          name?: string;
          platform?: string;
          status?: "draft" | "pending_approval" | "approved" | "active" | "completed" | "rejected";
          total_budget?: string;
          currency?: string;
          start_date?: string | null;
          end_date?: string | null;
          kpi_targets?: Record<string, unknown>;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      media_publishing_plan: {
        Row: {
          id: string;
          tenant_id: string;
          title: string;
          description: string | null;
          platform: string;
          content_type: string;
          status: "planned" | "in_progress" | "published" | "cancelled";
          scheduled_date: string;
          scheduled_time: string | null;
          assigned_to: string | null;
          content_url: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          title: string;
          description?: string | null;
          platform?: string;
          content_type?: string;
          status?: "planned" | "in_progress" | "published" | "cancelled";
          scheduled_date: string;
          scheduled_time?: string | null;
          assigned_to?: string | null;
          content_url?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          title?: string;
          description?: string | null;
          platform?: string;
          content_type?: string;
          status?: "planned" | "in_progress" | "published" | "cancelled";
          scheduled_date?: string;
          scheduled_time?: string | null;
          assigned_to?: string | null;
          content_url?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      product_variants: {
        Row: {
          id: string;
          product_id: string;
          tenant_id: string;
          name: string;
          name_en: string | null;
          name_zh: string | null;
          sku: string | null;
          price: number;
          currency: string;
          stock: number;
          image_url: string | null;
          attributes: Record<string, unknown>;
          is_active: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          tenant_id: string;
          name: string;
          name_en?: string | null;
          name_zh?: string | null;
          sku?: string | null;
          price?: number;
          currency?: string;
          stock?: number;
          image_url?: string | null;
          attributes?: Record<string, unknown>;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          tenant_id?: string;
          name?: string;
          name_en?: string | null;
          name_zh?: string | null;
          sku?: string | null;
          price?: number;
          currency?: string;
          stock?: number;
          image_url?: string | null;
          attributes?: Record<string, unknown>;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string | null;
          variant_id: string | null;
          product_name: string;
          variant_name: string | null;
          quantity: number;
          unit_price: number;
          discount_amount: number;
          line_total: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          product_id?: string | null;
          variant_id?: string | null;
          product_name: string;
          variant_name?: string | null;
          quantity?: number;
          unit_price?: number;
          discount_amount?: number;
          line_total?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          product_id?: string | null;
          variant_id?: string | null;
          product_name?: string;
          variant_name?: string | null;
          quantity?: number;
          unit_price?: number;
          discount_amount?: number;
          line_total?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      deals: {
        Row: {
          id: string;
          tenant_id: string;
          contact_id: string | null;
          title: string;
          value: number;
          currency: string;
          stage: "new_inquiry" | "quoted" | "follow_up" | "negotiation" | "closed_won" | "closed_lost";
          expected_close_date: string | null;
          assigned_to: string | null;
          source: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          contact_id?: string | null;
          title: string;
          value?: number;
          currency?: string;
          stage?: "new_inquiry" | "quoted" | "follow_up" | "negotiation" | "closed_won" | "closed_lost";
          expected_close_date?: string | null;
          assigned_to?: string | null;
          source?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          contact_id?: string | null;
          title?: string;
          value?: number;
          currency?: string;
          stage?: "new_inquiry" | "quoted" | "follow_up" | "negotiation" | "closed_won" | "closed_lost";
          expected_close_date?: string | null;
          assigned_to?: string | null;
          source?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      deal_activities: {
        Row: {
          id: string;
          deal_id: string;
          type: "note" | "call" | "email" | "meeting" | "stage_change" | "task";
          description: string | null;
          metadata: Record<string, unknown>;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          deal_id: string;
          type?: "note" | "call" | "email" | "meeting" | "stage_change" | "task";
          description?: string | null;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          deal_id?: string;
          type?: "note" | "call" | "email" | "meeting" | "stage_change" | "task";
          description?: string | null;
          metadata?: Record<string, unknown>;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: "super_admin" | "tenant_owner" | "tenant_admin" | "staff" | "customer";
      industry_template: "ecommerce" | "restaurant" | "fnb" | "beauty" | "service";
      subscription_status: "trialing" | "active" | "past_due" | "cancelled" | "expired";
      member_tier: "free" | "silver" | "gold" | "platinum";
      ai_message_role: "user" | "assistant" | "system";
      tenant_status: "active" | "trial" | "suspended" | "cancelled";
      plan_tier: "trial" | "starter" | "pro" | "business";
      pipeline_stage: "new_inquiry" | "quoted" | "follow_up" | "closed_won" | "closed_lost";
      order_status: "draft" | "confirmed" | "shipped" | "completed" | "cancelled";
      follow_up_status: "pending" | "completed" | "overdue" | "cancelled";
      message_direction: "inbound" | "outbound";
      message_type: "text" | "image" | "document" | "template";
      message_status: "sent" | "delivered" | "read" | "failed";
      follow_up_type: "manual" | "automated";
      webhook_status: "success" | "failed";
      ticket_status: "open" | "in_progress" | "resolved" | "closed";
      ticket_priority: "low" | "medium" | "high" | "urgent";
      campaign_status: "active" | "paused" | "draft" | "completed";
      automation_type: "trigger" | "sequence" | "scheduled" | "ai";
      referral_status: "active" | "pending" | "paused" | "completed";
      landing_page_status: "published" | "draft" | "archived";
      appointment_status: "pending" | "confirmed" | "completed" | "cancelled";
      reservation_status: "pending" | "confirmed" | "seated" | "completed" | "cancelled";
      staff_status: "available" | "busy" | "off";
      table_status: "available" | "occupied" | "reserved" | "cleaning";
      shipment_status: "pending" | "shipped" | "in_transit" | "completed" | "returned";
      delivery_status: "pending" | "confirmed" | "delivering" | "completed" | "failed";
      transaction_status: "pending" | "success" | "failed" | "refunded";
      inventory_movement: "in" | "out";
      supplier_status: "active" | "inactive";
      po_status: "draft" | "submitted" | "approved" | "received" | "cancelled";
      bill_type: "purchase" | "logistics" | "operation" | "other";
      bill_status: "pending" | "paid" | "overdue";
      finance_type: "income" | "expense";
      marketing_campaign_status: "draft" | "active" | "paused" | "completed";
      budget_type: "daily" | "lifetime";
      placement_status: "draft" | "pending_approval" | "approved" | "active" | "completed" | "rejected";
      media_status: "planned" | "in_progress" | "published" | "cancelled";
      deal_stage: "new_inquiry" | "quoted" | "follow_up" | "negotiation" | "closed_won" | "closed_lost";
      deal_activity_type: "note" | "call" | "email" | "meeting" | "stage_change" | "task";
      payment_status: "unpaid" | "partial" | "paid" | "refunded";
      discount_type: "percentage" | "fixed";
    };
  };
}

// Convenience type helpers
type Tables = Database["public"]["Tables"];
export type TableName = keyof Tables;
export type Row<T extends TableName> = Tables[T]["Row"];
export type Insert<T extends TableName> = Tables[T]["Insert"];
export type Update<T extends TableName> = Tables[T]["Update"];
